#!/usr/bin/env node
// add_saha_missing.mjs — eksik saha endpoint'leri kalıcı patcher
// Tablolar: saha_rep_not, saha_rep_profil, saha_rep_conversations,
//           saha_konusma, saha_konusma_mesaj, saha_duyuru, saha_oneri, saha_hata_log
// Çalıştır: node /opt/krb-assessment/add_saha_missing.mjs
import { readFileSync, writeFileSync } from "fs";

const TARGET = "/opt/krb-assessment/server.mjs";
const src = readFileSync(TARGET, "utf8");

if (src.includes('path === "/api/saha/notlar"')) {
  console.log("✓ Zaten eklenmiş — atlanıyor");
  process.exit(0);
}

const ANCHOR = 'sendJson(response, 404, { error: "Bilinmeyen saha endpoint\'i." });';
if (!src.includes(ANCHOR)) {
  console.error("✗ Anchor bulunamadı"); process.exit(1);
}

// UUID regex pattern (server.mjs'teki SAHA_UUID_RE yerine)
const UUID = "[0-9a-f-]{36}";

const lines = [
  "",
  "    // ══ NOTLARIM ════════════════════════════════════════════════════════════",
  "    // GET /api/saha/notlar — kişisel notlar listesi",
  '    if (method === "GET" && path === "/api/saha/notlar") {',
  "      const session = await requireSahaAccess(request);",
  "      const rows = await pool.query(",
  "        `SELECT id, icerik, hatirlatma_tarihi, tamamlandi, created_at, updated_at",
  "           FROM saha_rep_not",
  "          WHERE tenant_id = $1 AND rep_id = $2",
  "          ORDER BY created_at DESC LIMIT 100`,",
  "        [session.tenantId, session.userId]",
  "      );",
  "      sendJson(response, 200, { notlar: rows.rows });",
  "      return;",
  "    }",
  "",
  "    // POST /api/saha/notlar — not oluştur",
  '    if (method === "POST" && path === "/api/saha/notlar") {',
  "      const session = await requireSahaAccess(request);",
  "      const { icerik, hatirlatma_tarihi } = body;",
  "      if (!icerik) { sendJson(response, 400, { error: 'icerik zorunlu' }); return; }",
  "      const r = await pool.query(",
  "        `INSERT INTO saha_rep_not (id, tenant_id, rep_id, icerik, hatirlatma_tarihi)",
  "         VALUES (gen_random_uuid(), $1, $2, $3, $4) RETURNING *`,",
  "        [session.tenantId, session.userId, icerik, hatirlatma_tarihi || null]",
  "      );",
  "      sendJson(response, 201, { not: r.rows[0] });",
  "      return;",
  "    }",
  "",
  "    // PUT /api/saha/notlar/:id",
  `    if (method === "PUT" && (m = path.match(/^\\/api\\/saha\\/notlar\\/(${UUID})$/))) {`,
  "      const session = await requireSahaAccess(request);",
  "      const { icerik, hatirlatma_tarihi, tamamlandi } = body;",
  "      await pool.query(",
  "        `UPDATE saha_rep_not SET icerik=COALESCE($3,icerik),",
  "           hatirlatma_tarihi=COALESCE($4,hatirlatma_tarihi),",
  "           tamamlandi=COALESCE($5,tamamlandi), updated_at=now()",
  "         WHERE id=$1 AND rep_id=$2`,",
  "        [m[1], session.userId, icerik||null, hatirlatma_tarihi||null, tamamlandi??null]",
  "      );",
  "      sendJson(response, 200, { ok: true });",
  "      return;",
  "    }",
  "",
  "    // DELETE /api/saha/notlar/:id",
  `    if (method === "DELETE" && (m = path.match(/^\\/api\\/saha\\/notlar\\/(${UUID})$/))) {`,
  "      const session = await requireSahaAccess(request);",
  "      await pool.query(",
  "        'DELETE FROM saha_rep_not WHERE id=$1 AND rep_id=$2',",
  "        [m[1], session.userId]",
  "      );",
  "      sendJson(response, 200, { ok: true });",
  "      return;",
  "    }",
  "",
  "    // ══ REP PROFİL ═══════════════════════════════════════════════════════════",
  '    if (method === "GET" && path === "/api/saha/rep-profil") {',
  "      const session = await requireSahaAccess(request);",
  "      const r = await pool.query(",
  "        `SELECT base_adres, base_lat, base_lng FROM saha_rep_profil",
  "          WHERE tenant_id=$1 AND rep_id=$2`,",
  "        [session.tenantId, session.userId]",
  "      );",
  "      sendJson(response, 200, { profil: r.rows[0] || {} });",
  "      return;",
  "    }",
  '    if (method === "PUT" && path === "/api/saha/rep-profil") {',
  "      const session = await requireSahaAccess(request);",
  "      const { base_adres, base_lat, base_lng } = body;",
  "      await pool.query(",
  "        `INSERT INTO saha_rep_profil (tenant_id, rep_id, base_adres, base_lat, base_lng, updated_at)",
  "         VALUES ($1,$2,$3,$4,$5,now())",
  "         ON CONFLICT (tenant_id, rep_id) DO UPDATE",
  "         SET base_adres=$3, base_lat=$4, base_lng=$5, updated_at=now()`,",
  "        [session.tenantId, session.userId, base_adres||null, base_lat||null, base_lng||null]",
  "      );",
  "      sendJson(response, 200, { ok: true });",
  "      return;",
  "    }",
  "",
  "    // ══ REP BRAIN AI ═════════════════════════════════════════════════════════",
  '    if (method === "POST" && path === "/api/saha/rep-brain") {',
  "      const session = await requireSahaAccess(request);",
  "      const { mesaj } = body;",
  "      if (!mesaj) { sendJson(response, 400, { error: 'mesaj zorunlu' }); return; }",
  "      // Sohbet geçmişini kaydet",
  "      await pool.query(",
  "        `INSERT INTO saha_rep_conversations (tenant_id, rep_id, role, content)",
  "         VALUES ($1,$2,'user',$3)`,",
  "        [session.tenantId, session.userId, mesaj]",
  "      );",
  "      // Son 10 mesajı al",
  "      const hist = await pool.query(",
  "        `SELECT role, content FROM saha_rep_conversations",
  "          WHERE tenant_id=$1 AND rep_id=$2 ORDER BY id DESC LIMIT 10`,",
  "        [session.tenantId, session.userId]",
  "      );",
  "      const messages = [",
  '        { role: "system", content: "Sen KRB Otomotiv saha ekibinin kişisel asistanısın. Türkçe cevap ver. Kısa ve pratik ol." },',
  "        ...hist.rows.reverse().map(r => ({ role: r.role, content: r.content }))",
  "      ];",
  "      let yanit = 'Şu an yanıt veremiyorum, lütfen tekrar dene.';",
  "      try {",
  "        const aiRes = await fetch('https://api.anthropic.com/v1/messages', {",
  "          method: 'POST',",
  "          headers: {",
  "            'x-api-key': process.env.ANTHROPIC_API_KEY || '',",
  "            'anthropic-version': '2023-06-01',",
  "            'content-type': 'application/json'",
  "          },",
  "          body: JSON.stringify({",
  "            model: 'claude-haiku-4-5-20251001',",
  "            max_tokens: 800,",
  "            messages",
  "          })",
  "        });",
  "        const data = await aiRes.json();",
  "        yanit = data.content?.[0]?.text || yanit;",
  "      } catch(_) {}",
  "      // AI yanıtını kaydet",
  "      await pool.query(",
  "        `INSERT INTO saha_rep_conversations (tenant_id, rep_id, role, content)",
  "         VALUES ($1,$2,'assistant',$3)`,",
  "        [session.tenantId, session.userId, yanit]",
  "      );",
  "      sendJson(response, 200, { yanit });",
  "      return;",
  "    }",
  "",
  "    // ══ DUYURULAR ════════════════════════════════════════════════════════════",
  '    if (method === "GET" && path === "/api/saha/duyurular") {',
  "      const session = await requireSahaAccess(request);",
  "      const rows = await pool.query(",
  "        `SELECT d.id, d.yazan_adi, d.baslik, d.icerik, d.onem, d.created_at,",
  "                (SELECT count(*) FROM saha_duyuru_okundu o WHERE o.duyuru_id=d.id AND o.user_id=$2) > 0 AS okundu",
  "           FROM saha_duyuru d",
  "          WHERE d.tenant_id=$1 ORDER BY d.created_at DESC LIMIT 50`,",
  "        [session.tenantId, session.userId]",
  "      );",
  "      const okunmamis = rows.rows.filter(d => !d.okundu);",
  "      sendJson(response, 200, { duyurular: rows.rows, okunmamis_sayisi: okunmamis.length });",
  "      return;",
  "    }",
  '    if (method === "POST" && path === "/api/saha/duyurular") {',
  "      const session = await requireSahaAccess(request, ['manager','admin']);",
  "      const { baslik, icerik, onem='NORMAL' } = body;",
  "      if (!baslik || !icerik) { sendJson(response, 400, { error: 'baslik ve icerik zorunlu' }); return; }",
  "      const r = await pool.query(",
  "        `INSERT INTO saha_duyuru (id,tenant_id,yazan_id,yazan_adi,baslik,icerik,onem)",
  "         VALUES (gen_random_uuid(),$1,$2,$3,$4,$5,$6) RETURNING id`,",
  "        [session.tenantId, session.userId, session.name||'Yönetici', baslik, icerik, onem]",
  "      );",
  "      sendJson(response, 201, { id: r.rows[0].id });",
  "      return;",
  "    }",
  `    if (method === "PUT" && (m = path.match(/^\\/api\\/saha\\/duyurular\\/(${UUID})\\/oku$/))) {`,
  "      const session = await requireSahaAccess(request);",
  "      await pool.query(",
  "        `INSERT INTO saha_duyuru_okundu (duyuru_id, user_id, tenant_id)",
  "         VALUES ($1,$2,$3) ON CONFLICT DO NOTHING`,",
  "        [m[1], session.userId, session.tenantId]",
  "      );",
  "      sendJson(response, 200, { ok: true });",
  "      return;",
  "    }",
  "",
  "    // ══ KONUŞMALAR (mesajlar) ════════════════════════════════════════════════",
  '    if (method === "GET" && path === "/api/saha/konusmalar") {',
  "      const session = await requireSahaAccess(request);",
  "      let sql, params;",
  "      if (session.sahaRole === 'rep') {",
  "        sql = `SELECT k.id, k.tip, k.created_at,",
  "                (SELECT icerik FROM saha_konusma_mesaj WHERE konusma_id=k.id ORDER BY created_at DESC LIMIT 1) AS son_mesaj,",
  "                (SELECT gonderen_adi FROM saha_konusma_mesaj WHERE konusma_id=k.id ORDER BY created_at DESC LIMIT 1) AS son_gonderen",
  "               FROM saha_konusma k WHERE k.tenant_id=$1 AND k.rep_id=$2 ORDER BY k.created_at DESC`;",
  "        params = [session.tenantId, session.userId];",
  "      } else {",
  "        sql = `SELECT k.id, k.tip, k.rep_id, k.created_at,",
  "                (SELECT icerik FROM saha_konusma_mesaj WHERE konusma_id=k.id ORDER BY created_at DESC LIMIT 1) AS son_mesaj,",
  "                (SELECT gonderen_adi FROM saha_konusma_mesaj WHERE konusma_id=k.id ORDER BY created_at DESC LIMIT 1) AS son_gonderen",
  "               FROM saha_konusma k WHERE k.tenant_id=$1 ORDER BY k.created_at DESC LIMIT 100`;",
  "        params = [session.tenantId];",
  "      }",
  "      const rows = await pool.query(sql, params);",
  "      sendJson(response, 200, { konusmalar: rows.rows });",
  "      return;",
  "    }",
  `    if (method === "GET" && (m = path.match(/^\\/api\\/saha\\/konusmalar\\/(${UUID})\\/mesajlar$/))) {`,
  "      const session = await requireSahaAccess(request);",
  "      const rows = await pool.query(",
  "        `SELECT id, gonderen_id, gonderen_adi, gonderen_rol, icerik, created_at",
  "           FROM saha_konusma_mesaj WHERE konusma_id=$1 AND tenant_id=$2",
  "           ORDER BY created_at ASC LIMIT 200`,",
  "        [m[1], session.tenantId]",
  "      );",
  "      sendJson(response, 200, { mesajlar: rows.rows });",
  "      return;",
  "    }",
  '    if (method === "POST" && path === "/api/saha/konusmalar") {',
  "      const session = await requireSahaAccess(request);",
  "      const { rep_id, icerik, tip='rep-manager' } = body;",
  "      if (!icerik) { sendJson(response, 400, { error: 'icerik zorunlu' }); return; }",
  "      const targetRepId = rep_id || session.userId;",
  "      // Konuşma bul veya oluştur",
  "      let kRes = await pool.query(",
  "        `SELECT id FROM saha_konusma WHERE tenant_id=$1 AND rep_id=$2 AND tip=$3 LIMIT 1`,",
  "        [session.tenantId, targetRepId, tip]",
  "      );",
  "      let konusmaId;",
  "      if (kRes.rows.length) {",
  "        konusmaId = kRes.rows[0].id;",
  "      } else {",
  "        const ins = await pool.query(",
  "          `INSERT INTO saha_konusma (id,tenant_id,tip,rep_id) VALUES (gen_random_uuid(),$1,$2,$3) RETURNING id`,",
  "          [session.tenantId, tip, targetRepId]",
  "        );",
  "        konusmaId = ins.rows[0].id;",
  "      }",
  "      // Mesajı ekle",
  "      await pool.query(",
  "        `INSERT INTO saha_konusma_mesaj (id,tenant_id,konusma_id,gonderen_id,gonderen_adi,gonderen_rol,icerik)",
  "         VALUES (gen_random_uuid(),$1,$2,$3,$4,$5,$6)`,",
  "        [session.tenantId, konusmaId, session.userId, session.name||'Kullanıcı', session.sahaRole||'rep', icerik]",
  "      );",
  "      sendJson(response, 201, { konusma_id: konusmaId });",
  "      return;",
  "    }",
  '    if (method === "POST" && path === "/api/saha/konusmalar/coklu") {',
  "      const session = await requireSahaAccess(request, ['manager','admin']);",
  "      const { rep_ids, icerik } = body;",
  "      if (!Array.isArray(rep_ids) || !icerik) { sendJson(response, 400, { error: 'rep_ids ve icerik zorunlu' }); return; }",
  "      for (const rid of rep_ids) {",
  "        let kRes = await pool.query(",
  "          `SELECT id FROM saha_konusma WHERE tenant_id=$1 AND rep_id=$2 AND tip='rep-manager' LIMIT 1`,",
  "          [session.tenantId, rid]",
  "        );",
  "        let konusmaId;",
  "        if (kRes.rows.length) { konusmaId = kRes.rows[0].id; }",
  "        else {",
  "          const ins = await pool.query(",
  "            `INSERT INTO saha_konusma (id,tenant_id,tip,rep_id) VALUES (gen_random_uuid(),$1,'rep-manager',$2) RETURNING id`,",
  "            [session.tenantId, rid]",
  "          );",
  "          konusmaId = ins.rows[0].id;",
  "        }",
  "        await pool.query(",
  "          `INSERT INTO saha_konusma_mesaj (id,tenant_id,konusma_id,gonderen_id,gonderen_adi,gonderen_rol,icerik)",
  "           VALUES (gen_random_uuid(),$1,$2,$3,$4,'manager',$5)`,",
  "          [session.tenantId, konusmaId, session.userId, session.name||'Yönetici', icerik]",
  "        );",
  "      }",
  "      sendJson(response, 200, { ok: true, sayi: rep_ids.length });",
  "      return;",
  "    }",
  '    if (method === "POST" && path === "/api/saha/konusmalar/yayim") {',
  "      const session = await requireSahaAccess(request, ['manager','admin']);",
  "      const { icerik } = body;",
  "      if (!icerik) { sendJson(response, 400, { error: 'icerik zorunlu' }); return; }",
  "      const reps = await pool.query(",
  "        `SELECT DISTINCT rep_id FROM saha_konusma WHERE tenant_id=$1`,",
  "        [session.tenantId]",
  "      );",
  "      for (const r of reps.rows) {",
  "        let kRes = await pool.query(",
  "          `SELECT id FROM saha_konusma WHERE tenant_id=$1 AND rep_id=$2 AND tip='rep-manager' LIMIT 1`,",
  "          [session.tenantId, r.rep_id]",
  "        );",
  "        if (kRes.rows.length) {",
  "          await pool.query(",
  "            `INSERT INTO saha_konusma_mesaj (id,tenant_id,konusma_id,gonderen_id,gonderen_adi,gonderen_rol,icerik)",
  "             VALUES (gen_random_uuid(),$1,$2,$3,$4,'manager',$5)`,",
  "            [session.tenantId, kRes.rows[0].id, session.userId, session.name||'Yönetici', icerik]",
  "          );",
  "        }",
  "      }",
  "      sendJson(response, 200, { ok: true });",
  "      return;",
  "    }",
  "",
  "    // ══ ÖNERİLER ════════════════════════════════════════════════════════════",
  '    if (method === "GET" && path === "/api/saha/oneriler") {',
  "      const session = await requireSahaAccess(request);",
  "      let sql = `SELECT id, kategori, baslik, mesaj, durum, yonetici_notu, ts, guncellendi_at",
  "                   FROM saha_oneri WHERE tenant_id=$1`;",
  "      const p = [session.tenantId];",
  "      if (session.sahaRole === 'rep') { sql += ' AND user_id=$2'; p.push(session.userId); }",
  "      sql += ' ORDER BY ts DESC LIMIT 50';",
  "      const rows = await pool.query(sql, p);",
  "      sendJson(response, 200, { oneriler: rows.rows });",
  "      return;",
  "    }",
  '    if (method === "POST" && path === "/api/saha/oneri") {',
  "      const session = await requireSahaAccess(request);",
  "      const { kategori='GENEL', baslik, mesaj } = body;",
  "      if (!baslik || !mesaj) { sendJson(response, 400, { error: 'baslik ve mesaj zorunlu' }); return; }",
  "      await pool.query(",
  "        `INSERT INTO saha_oneri (id,tenant_id,user_id,kategori,baslik,mesaj,durum)",
  "         VALUES (gen_random_uuid(),$1,$2,$3,$4,$5,'BEKLEMEDE')`,",
  "        [session.tenantId, session.userId, kategori, baslik, mesaj]",
  "      );",
  "      sendJson(response, 201, { ok: true });",
  "      return;",
  "    }",
  `    if (method === "PUT" && (m = path.match(/^\\/api\\/saha\\/oneriler\\/(${UUID})$/))) {`,
  "      const session = await requireSahaAccess(request, ['manager','admin']);",
  "      const { durum, yonetici_notu } = body;",
  "      await pool.query(",
  "        `UPDATE saha_oneri SET durum=COALESCE($2,durum), yonetici_notu=COALESCE($3,yonetici_notu), guncellendi_at=now() WHERE id=$1`,",
  "        [m[1], durum||null, yonetici_notu||null]",
  "      );",
  "      sendJson(response, 200, { ok: true });",
  "      return;",
  "    }",
  "",
  "    // ══ LOG / HATA ═══════════════════════════════════════════════════════════",
  '    if (method === "POST" && path === "/api/saha/log-hata") {',
  "      // Sessiz hata logu — auth gerekmez",
  "      try {",
  "        const { tip, view_adi, endpoint, http_status, hata_mesaji, duration_ms, extra } = body;",
  "        await pool.query(",
  "          `INSERT INTO saha_hata_log (id,tenant_id,user_id,tip,view_adi,endpoint,http_status,hata_mesaji,duration_ms,extra)",
  "           VALUES (gen_random_uuid(),$1,$2,$3,$4,$5,$6,$7,$8,$9)`,",
  "          ['00000000-0000-0000-0000-000000000000', null, tip||'client', view_adi||null,",
  "           endpoint||null, http_status||null, hata_mesaji||null, duration_ms||null,",
  "           extra ? JSON.stringify(extra) : null]",
  "        );",
  "      } catch(_) {}",
  "      sendJson(response, 200, { ok: true });",
  "      return;",
  "    }",
  '    if (method === "POST" && path === "/api/saha/hata-raporu") {',
  "      const session = await requireSahaAccess(request);",
  "      const { tip='manual', view_adi, endpoint, hata_mesaji, extra } = body;",
  "      await pool.query(",
  "        `INSERT INTO saha_hata_log (id,tenant_id,user_id,tip,view_adi,endpoint,hata_mesaji,extra)",
  "         VALUES (gen_random_uuid(),$1,$2,$3,$4,$5,$6,$7)`,",
  "        [session.tenantId, session.userId, tip, view_adi||null, endpoint||null,",
  "         hata_mesaji||null, extra ? JSON.stringify(extra) : null]",
  "      );",
  "      sendJson(response, 200, { ok: true });",
  "      return;",
  "    }",
  "",
];

const PATCH = lines.join("\n");
const patched = src.replace(ANCHOR, PATCH + "    " + ANCHOR);
writeFileSync(TARGET, patched, "utf8");

const added = [
  "/api/saha/notlar (GET/POST/PUT/DELETE)",
  "/api/saha/rep-profil (GET/PUT)",
  "/api/saha/rep-brain (POST)",
  "/api/saha/duyurular (GET/POST + oku)",
  "/api/saha/konusmalar (GET/POST + coklu + yayim + mesajlar)",
  "/api/saha/oneriler (GET) + /api/saha/oneri (POST/PUT)",
  "/api/saha/log-hata (POST) + /api/saha/hata-raporu (POST)",
];
added.forEach(e => console.log("✓", e));
console.log(`  Toplam satır: ${patched.split("\n").length}`);
