#!/usr/bin/env bash
# FINPARSE_FIX_V2 deploy — salvage parser + max_tokens 4000. Boş satırı sil, rebuild, regen, doğrula.
set -e
cd /opt/krb-assessment
set -a; [ -f .env ] && . ./.env; set +a
PW="${POSTGRES_PASSWORD:-}"
cp server_container.mjs server_container.mjs.bak.$(date +%s)
printf '%s' 'IyEvdXNyL2Jpbi9lbnYgcHl0aG9uMwojIEZJTlBBUlNFX0ZJWF9WMiDigJQgcGFyc2UnxLEgdHJ1bmNhdGlvbidhIGRheWFuxLFrbMSxIHlhcDogKGEpIG1heF90b2tlbnMgMjIwMC0+NDAwMCwKIyAoYikgc2FsdmFnZTogZGl6aSBib3p1a3NhIGhlciB0YW0ge+KApn0gbmVzbmVzaW5pIHRlayB0ZWsgcGFyc2UgZXQgKGtlc2lrIHNvbiBuZXNuZSBkw7zFn2VyKSwKIyAoYykgc3RyaW5nLWnDp2kgbGl0ZXJhbCBuZXdsaW5lJ2xhcsSxIG5vcm1hbGl6ZSBldC4gSWRlbXBvdGVudC4gRklOUEFSU0VfRklYX1YxIGJsb8SfdW51IGRlxJ9pxZ90aXJpci4KZGVmIHJlYWQocCk6IHJldHVybiBvcGVuKHAsIGVuY29kaW5nPSJ1dGYtOCIpLnJlYWQoKQpkZWYgd3JpdGUocCwgcyk6IG9wZW4ocCwgInciLCBlbmNvZGluZz0idXRmLTgiKS53cml0ZShzKQoKRlAgPSAic2VydmVyX2NvbnRhaW5lci5tanMiCnMgPSByZWFkKEZQKQppZiAiRklOUEFSU0VfRklYX1YyIiBpbiBzOgogICAgcHJpbnQoImZpbnBhcnNlMjogYWxyZWFkeSBwcmVzZW50LCBza2lwIik7IHByaW50KCJET05FLiIpOyByYWlzZSBTeXN0ZW1FeGl0CgojICgxKSBtYXhfdG9rZW5zIDIyMDAgLT4gNDAwMAphMCA9ICdtb2RlbDogImNsYXVkZS1zb25uZXQtNC02IiwgbWF4X3Rva2VuczogMjIwMCwgc3lzdGVtOiBfRklOX1NZUywgLy8gRklOUEFSU0VfRklYX1YxJwpuMCA9ICdtb2RlbDogImNsYXVkZS1zb25uZXQtNC02IiwgbWF4X3Rva2VuczogNDAwMCwgc3lzdGVtOiBfRklOX1NZUywgLy8gRklOUEFSU0VfRklYX1YyJwphc3NlcnQgcy5jb3VudChhMCkgPT0gMSwgIm1heF90b2tlbnMgYW5jaG9yIgpzID0gcy5yZXBsYWNlKGEwLCBuMCwgMSkKCiMgKDIpIEZJTlBBUlNFX0ZJWF9WMSBwYXJzZSBibG/En3VudSBWMiAoc2FsdmFnZSkgaWxlIGRlxJ9pxZ90aXIKb2xkID0gKCcgIGxldCByYXcgPSAobXNnLmNvbnRlbnQgfHwgW10pLmZpbHRlcih4ID0+IHgudHlwZSA9PT0gInRleHQiKS5tYXAoeCA9PiB4LnRleHQpLmpvaW4oIiIpLnRyaW0oKTtcbicKICAgICAgICcgIGxldCB0eHQgPSByYXcucmVwbGFjZSgvYGBganNvbi9naSwgIiIpLnJlcGxhY2UoL2BgYC9nLCAiIikudHJpbSgpO1xuJwogICAgICAgJyAgY29uc3QgX3RwID0gKHQpID0+IHsgdHJ5IHsgcmV0dXJuIEpTT04ucGFyc2UodCk7IH0gY2F0Y2ggKGUpIHsgcmV0dXJuIG51bGw7IH0gfTtcbicKICAgICAgICcgIGxldCBhcnIgPSBudWxsO1xuJwogICAgICAgJyAgbGV0IHAgPSBfdHAodHh0KTtcbicKICAgICAgICcgIGlmIChwICYmICFBcnJheS5pc0FycmF5KHApICYmIEFycmF5LmlzQXJyYXkocC5pY2dvcnVsZXIpKSBwID0gcC5pY2dvcnVsZXI7XG4nCiAgICAgICAnICBpZiAoQXJyYXkuaXNBcnJheShwKSkgYXJyID0gcDtcbicKICAgICAgICcgIGlmICghYXJyKSB7IGNvbnN0IGkgPSB0eHQuaW5kZXhPZigiWyIpLCBqID0gdHh0Lmxhc3RJbmRleE9mKCJdIik7IGlmIChpID49IDAgJiYgaiA+IGkpIHsgY29uc3QgcDIgPSBfdHAodHh0LnNsaWNlKGksIGogKyAxKSk7IGlmIChBcnJheS5pc0FycmF5KHAyKSkgYXJyID0gcDI7IH0gfVxuJwogICAgICAgJyAgaWYgKCFBcnJheS5pc0FycmF5KGFycikpIGFyciA9IFtdO1xuJwogICAgICAgJyAgaWYgKCFhcnIubGVuZ3RoKSB7IGNvbnNvbGUuZXJyb3IoIltmaW4taWNnb3J1XSBwYXJzZSBib3MgLSBoYW0oMC4uMzAwKToiLCByYXcuc2xpY2UoMCwgMzAwKSk7IGN0eC5faGFtID0gcmF3LnNsaWNlKDAsIDgwMCk7IH1cbicKICAgICAgICcgIHJldHVybiB7IGljZ29ydWxlcjogYXJyLCBiYWdsYW06IGN0eCB9OycpCm5ldyA9ICgnICBsZXQgcmF3ID0gKG1zZy5jb250ZW50IHx8IFtdKS5maWx0ZXIoeCA9PiB4LnR5cGUgPT09ICJ0ZXh0IikubWFwKHggPT4geC50ZXh0KS5qb2luKCIiKS50cmltKCk7IC8vIEZJTlBBUlNFX0ZJWF9WMlxuJwogICAgICAgJyAgbGV0IHR4dCA9IHJhdy5yZXBsYWNlKC9gYGBqc29uL2dpLCAiIikucmVwbGFjZSgvYGBgL2csICIiKS50cmltKCk7XG4nCiAgICAgICAnICBjb25zdCBfdHAgPSAodCkgPT4geyB0cnkgeyByZXR1cm4gSlNPTi5wYXJzZSh0KTsgfSBjYXRjaCAoZSkgeyByZXR1cm4gbnVsbDsgfSB9O1xuJwogICAgICAgJyAgY29uc3QgX25vcm0gPSAodCkgPT4gdC5yZXBsYWNlKC9bXFxyXFxuXFx0XSsvZywgIiAiKTtcbicKICAgICAgICcgIGxldCBhcnIgPSBudWxsO1xuJwogICAgICAgJyAgZm9yIChjb25zdCBjYW5kIG9mIFt0eHQsIF9ub3JtKHR4dCldKSB7XG4nCiAgICAgICAnICAgIGxldCBwID0gX3RwKGNhbmQpO1xuJwogICAgICAgJyAgICBpZiAocCAmJiAhQXJyYXkuaXNBcnJheShwKSAmJiBBcnJheS5pc0FycmF5KHAuaWNnb3J1bGVyKSkgcCA9IHAuaWNnb3J1bGVyO1xuJwogICAgICAgJyAgICBpZiAoQXJyYXkuaXNBcnJheShwKSkgeyBhcnIgPSBwOyBicmVhazsgfVxuJwogICAgICAgJyAgICBjb25zdCBpID0gY2FuZC5pbmRleE9mKCJbIiksIGogPSBjYW5kLmxhc3RJbmRleE9mKCJdIik7XG4nCiAgICAgICAnICAgIGlmIChpID49IDAgJiYgaiA+IGkpIHsgY29uc3QgcDIgPSBfdHAoY2FuZC5zbGljZShpLCBqICsgMSkpOyBpZiAoQXJyYXkuaXNBcnJheShwMikpIHsgYXJyID0gcDI7IGJyZWFrOyB9IH1cbicKICAgICAgICcgIH1cbicKICAgICAgICcgIGlmICghYXJyIHx8ICFhcnIubGVuZ3RoKSB7XG4nCiAgICAgICAnICAgIGNvbnN0IG9ianMgPSBfbm9ybSh0eHQpLm1hdGNoKC9cXHtbXnt9XSpcXH0vZykgfHwgW107XG4nCiAgICAgICAnICAgIGNvbnN0IHNhbCA9IFtdO1xuJwogICAgICAgJyAgICBmb3IgKGNvbnN0IG8gb2Ygb2JqcykgeyBjb25zdCB4ID0gX3RwKG8pOyBpZiAoeCAmJiAoeC5iYXNsaWsgfHwgeC5vemV0KSkgc2FsLnB1c2goeCk7IH1cbicKICAgICAgICcgICAgaWYgKHNhbC5sZW5ndGgpIGFyciA9IHNhbDtcbicKICAgICAgICcgIH1cbicKICAgICAgICcgIGlmICghQXJyYXkuaXNBcnJheShhcnIpKSBhcnIgPSBbXTtcbicKICAgICAgICcgIGlmICghYXJyLmxlbmd0aCkgeyBjb25zb2xlLmVycm9yKCJbZmluLWljZ29ydV0gcGFyc2UgYm9zIC0gaGFtKDAuLjMwMCk6IiwgcmF3LnNsaWNlKDAsIDMwMCkpOyBjdHguX2hhbSA9IHJhdy5zbGljZSgwLCA4MDApOyB9XG4nCiAgICAgICAnICByZXR1cm4geyBpY2dvcnVsZXI6IGFyciwgYmFnbGFtOiBjdHggfTsnKQphc3NlcnQgcy5jb3VudChvbGQpID09IDEsICJWMSBwYXJzZSBibG9jayBhbmNob3IiCnMgPSBzLnJlcGxhY2Uob2xkLCBuZXcsIDEpCgp3cml0ZShGUCwgcykKcHJpbnQoImZpbnBhcnNlMjogc2FsdmFnZSBwYXJzZXIgKyBtYXhfdG9rZW5zIDQwMDAiKQpwcmludCgiRE9ORS4iKQo=' | base64 -d > fix_finparse2.py
python3 fix_finparse2.py
node --check server_container.mjs && echo SERVER_OK
echo "== bugünkü boş satırı sil =="
docker exec -i -e PGPASSWORD="$PW" krb-assessment-postgres \
  psql -U assessment_app -d assessment_platform -P pager=off -c \
  "DELETE FROM bi_finansal_icgoru WHERE gun=CURRENT_DATE AND jsonb_array_length(icgoruler)=0;"
docker build -t krb-assessment:secure .
docker compose up -d --force-recreate krb-assessment
echo "== 95sn bekle =="
sleep 95
echo "== tablo =="
docker exec -i -e PGPASSWORD="$PW" krb-assessment-postgres \
  psql -U assessment_app -d assessment_platform -P pager=off -c \
  "SELECT to_char(gun,'YYYY-MM-DD') gun, jsonb_array_length(icgoruler) n, to_char(uretildi_at,'HH24:MI:SS') uretim FROM bi_finansal_icgoru ORDER BY uretildi_at DESC LIMIT 3;"
echo "== içgörü başlıkları + etki =="
docker exec -i -e PGPASSWORD="$PW" krb-assessment-postgres \
  psql -U assessment_app -d assessment_platform -P pager=off <<'SQL'
SELECT (e->>'siddet') siddet, left(e->>'baslik',48) baslik, e->>'etki_tl' etki_tl
FROM bi_finansal_icgoru, jsonb_array_elements(icgoruler) e
WHERE gun=CURRENT_DATE;
SQL
echo "-- loglar --"
docker logs --tail 300 krb-assessment 2>&1 | grep -i "fin-icgoru" | tail -6 || echo "(log yok)"
echo "== DONE =="
